version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./public:/app/public
      - /app/vendor
      - ./env.example:/app/.env
    environment:
      - COMPOSER_HOME=app/composer
      - COMPOSER_CACHE_DIR=app/composer/cache
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`laravel.localhost`)"
      - "traefik.http.services.laravel.loadbalancer.server.port=8000"
    networks:
      - web

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - web

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis:/data
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  database:
  redis:
