# Configuration statique de Traefik (traefik.yml)

# Points d'entrée (ports d'écoute)
entryPoints:
  web:
    address: ":80"
    # Optionnel: Redirection HTTP vers HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"
    # Optionnel: Configuration TLS par défaut
    # http:
    #   tls:
    #     certResolver: myresolver # Nom du résolveur de certificats

# Providers (comment Traefik découvre les services)
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # Socket Docker
    exposedByDefault: false # Important: N'expose que les conteneurs avec le label "traefik.enable=true"
    network: laravel-octane-network # Nom du réseau Docker par défaut à utiliser

# API et Dashboard
api:
  dashboard: true   # Activer le dashboard
  insecure: true    # ATTENTION: Pour le développement seulement.
                    # En production: false et configurer l'authentification via middleware.

# Configuration des logs (optionnel)
log:
  level: INFO # DEBUG, INFO, WARNING, ERROR

# Résolveurs de certificats (Exemple Let's Encrypt - à adapter)
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: votre-email@domaine.com
#       storage: /etc/traefik/acme/acme.json # Chemin interne à Traefik
#       # Choisir un challenge (http ou dns)
#       httpChallenge:
#         entryPoint: web # Utilise le port 80
#       # dnsChallenge:
#       #   provider: "cloudflare" # Ou autre provider supporté
#       #   # Variables d'environnement spécifiques au provider DNS nécessaires